### ISSUE TITLE
Filtering bar

### ISSUE THREAD

**Issue by edouardmisset** [WildCodeSchool/lyon-js-react-march21-g2-p2#22]
## Story

As a user I want to select a filtering criteria to only see a subset of movies

## Criteria & special considerations

- Create an input element with the filtering criteria's (genre & decade).

## Test scenario

- On the movie page I can see the filtering bar

## Tasks

- [] Create a div with 2 inputs : one with the available filtering criteria (genre, decade...), the other with its options (drama, action...)

**Comment by dorianeGH** [comment]
syntax of code: all good and clear
acceptance criteria : ok
test : home Page is not working for me anymore
Genre criteria does not always work, even after few minutes after the reloading
